### ISSUE TITLE
Board canvases don't render (Firefox, Chrome - Windows 10)

### ISSUE THREAD

**Issue by mat1jaczyyy** [davdav1233/tetris#1] opened 2019-02-11 11:20 UTC
Hey there, the board canvases don't render for me. I can see them fine on my phone (Chrome - Android 7), but not on the computer. 

Here's Firefox on Windows 10:
![image](https://user-images.githubusercontent.com/13300194/52560048-653a4380-2df7-11e9-811e-d61099caddfd.png)

And here's Chrome on Windows 10:
![image](https://user-images.githubusercontent.com/13300194/52560082-75eab980-2df7-11e9-8335-d8d963749885.png)

**Comment by davdav1233** [comment] 2019-02-15 03:26
Thanks for the report. I can reproduce the issue on Edge, but can't reproduce this issue on Firefox 65/Firefox Dev Edition 66/Chrome 72 on Windows Build 17134.

I'm assuming that this issue is also happening on Chrome on your computer. What version of Firefox and Windows are you using?

**Comment by mat1jaczyyy** [comment] 2019-02-16 22:08
![image](https://user-images.githubusercontent.com/13300194/52905801-c4f17e00-323f-11e9-87e7-b0fb02e92088.png)
![image](https://user-images.githubusercontent.com/13300194/52905803-cc188c00-323f-11e9-9d70-ae040ab0c08b.png)

**Comment by davdav1233** [comment] 2019-02-17 22:33
This issue has been fixed with 66e3572. Basically the issue was me forgetting to add a line to adjusts the `canvas` size even when the display is not hidpi, after refactoring the code some time ago. Thanks for opening the issue.

**Closed by davdav1233** 2019-02-17 22:33 UTC
